name: Code analysis

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
    - name: instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/local.txt
    - name: testes automatizados
      run: |
        pytest -vv --diff-symbols --cov carreira
    - name: análise estática de código
      run: |
        pylint carreira
    - name: análise de convenções de estilo
      run: |
        pycodestyle carreira